### ISSUE TITLE
关于attention score计算的一点疑问

### ISSUE THREAD

**Issue by hijupiter** [GuangtaoLyu/FETNet#4]
作者你好：
关于Text_Texture_Erase_And_Enhance_Module里面attention score的计算有点疑问
https://github.com/GuangtaoLyu/FETNet/blob/c8357ea4f8617b2b33f2e41f6f534d448786520e/modules/FETNet.py#L138

`self.softmax` = nn.Softmax(dim=1)
f1 = x_1.view(m_batchsize, -1, width * height)
b_att = torch.bmm(f1.permute(0, 2, 1), f1)
f1 = x_mask.view(m_batchsize, -1, width * height)
mask_att = torch.bmm(f1.permute(0, 2, 1), f1)
b_att = b_att * mask_att
b_att = b_att.view(m_batchsize, -1, width, height)
b_att = self.softmax(b_att)`

b_att 的计算是（batchsize，查询query，维度dim，）@ （batchsize，维度dim，查询key，）=（batchsize，查询query，查询key）
这里的softmax源码是(dim=1)而不是（dim-1），请问为什么不是在查询key做softmax？

**Comment by GuangtaoLyu** [comment]
我这个是空间方面的操作，自然是要处理通道那一维度。
